const statusCode={
    "SUCCESS":true,
    "FAILURE":false,
    "HTTP_SUCCESS":200,
    "HTTP_BAD-REQUEST":400,
    "HTTP_ISE":500,
}

const message={
    success:{
        "PLACE_ORDER":"ORDER WAS SUCCESSFULLY CREATED !",
        "MODIFY_ORDER":"ORDER WAS SUCCESSFULLY MODIFIED !",
        "DELETE_ORDER":"THE ORDER WAS SUCCESSFULLY CANCELLED !"  
    },
    error:{
        "INPUT_ERROR":"INVALID REQUEST PARAMETERS",        
        "ID_ERROR":"NO ORDER FOUND WITH THAT ID",
        "INT_SER_ERROR":"SOMETHING WENT WRONG !",
        "ERR_PLACE_ORDER":"THERE WAS ERROR WHILE PLACING YOUR ORDER!",
        "NOT_AN_OPEN_ORDER":"ORDER IS CURRENTLY NOT IN OPEN STATUS ",
        "DB_ERROR":"THIS ORDER CAN'T BE MODIFIED AT THIS MOMENT",
        "ERR_MODIFY_ORDER":"THERE WAS ERROR WHILE MODIFYING THIS ORDER",
        "ERR_DELETE_ORDER":"THERE WAS ERROR WHILE DELETING THIS ORDER",
        "REQUESTED_QUANTITY":"THE REQUESTED QUANTITY IS NOT AVAILABLE",
        "DELETE_ORDER":"THE REQUESTED ORDER CAN'T BE CANCELLED AT THE MOMENT , BCOZ IT'S NOT IN OPEN STATUS",
    }
}

module.exports = {
    message,
    statusCode
}